services:
  frontend:
    build: .
    container_name: frontend-server
    env_file: '.env'
    environment:
      MODE: ${MODE}
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_PORT: ${FRONTEND_PORT}
    network_mode: 'host'
