services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: p1_fastapi_backend
    env_file: '.env'
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      BACKEND_PORT: ${BACKEND_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    volumes:
      - .:/app
    networks:
      - app_network
    command: python -m uvicorn src.app:app --port ${BACKEND_PORT} --host 0.0.0.0

networks:
  app_network:
    external: true
