services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: p1_fastapi
    env_file: '.env'
    ports:
      - '${FASTAPI_PORT}:${FASTAPI_PORT}'
    environment:
      DB_HOST: p1_fastapi_db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FASTAPI_PORT: ${FASTAPI_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: python -m uvicorn src.app:app --port ${FASTAPI_PORT} --host 0.0.0.0

  db:
    image: postgres:15-alpine
    container_name: p1_fastapi_db
    env_file: '.env'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin_user -d metrics_db']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
