services:
  db:
    image: postgres:15-alpine
    container_name: database-server
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin_user -d metrics_db']
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: '.env'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    network_mode: 'host' # default port is 5432
    restart: unless-stopped

volumes:
  pgdata:
