# ---------------------------------------------------------------------
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# ---------------------------------------------------------------------
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust
# Only allow connections from backend subnet range.
host    metrics_db      admin_user      10.0.2.0/24             scram-sha-256